### ISSUE TITLE
definedPages

### ISSUE THREAD

**Issue by beegegroup** [heimrichhannot/contao-navigation_plus#2]
Could it be, that in ModuleNavigation.php line 27 needs to be replaced as follows?
		$arrOrder = deserialize($this->pages, true);

**Comment by koertho** [comment]
Hi, thanks for reporting. First, please always provide contao-, bundle- and php-version. 
You issues is a good example for what could be provided as pull request ;)
Additional, this is an extension we don't use actively anymore, just some maintaining for legacy projects. So an PR would help since we do not really work on the code anymore.

**Comment by beegegroup** [comment]
#3

**Comment by koertho** [comment]
Fixed in 1.0.2
